#!/usr/bin/env python

import MySQLdb

db = MySQLdb.connect(host="127.0.0.1", user='kippo', passwd='kippopassword', db='kippo')

cur = db.cursor()
cur.execute("SELECT password from auth")
for row in cur.fetchall():
  print row[0]
